#!/usr/bin/env python3
r"""
translate_catalog.py — QuickScanZ i18n dictionary generator (self-hosted IndicTrans2)

WHAT IT DOES
------------
Reads an English-only catalog (catalog_en.json: { "key": "English text", ... })
and produces lib/i18n/messages.json with all 6 languages:
    en (source) + hi, te, ta, kn, ml  (machine-translated by IndicTrans2)

English is the single source of truth. Re-run this any time strings change.

WHY THIS MODEL
--------------
ai4bharat/indictrans2-en-indic-dist-200M  — distilled, MIT-licensed, runs on CPU.
Good enough for a one-off batch of short UI strings on the Toshiba laptop.
(For higher quality use ...-en-indic-1B, but it needs more RAM / is slower on CPU.)

SETUP  (see SETUP_indictrans2.md for the full walkthrough)
-----
    python3 -m venv venv && source venv/bin/activate      # (Windows: venv\Scripts\activate)
    pip install torch transformers sentencepiece
    pip install git+https://github.com/VarunGumma/IndicTransToolkit.git

RUN
---
    python translate_catalog.py --in catalog_en.json --out messages.json

NOTES
-----
* Output is written as UTF-8 (ensure_ascii=False). When committing the result,
  push it through the Pranix gateway (github_apply_patch) OR ensure your editor
  saves UTF-8 — do NOT let a Windows/PowerShell pipeline re-encode it, or the
  Indic text will corrupt back into "?" characters.
* Brand names / acronyms in DO_NOT_TRANSLATE are kept in English.
* Keep dynamic values (names, counts, prices) OUT of the strings — compose them
  in code. e.g. use key "dashboard.hello" = "Hello" and append the name in JSX.
* If your IndicTransToolkit version has a slightly different decode call, see the
  official notebook: huggingface_interface/colab_inference.ipynb in the IndicTrans2 repo.
"""

import argparse
import json
import sys

# ---- Configuration ---------------------------------------------------------

MODEL_NAME = "prajdabre/rotary-indictrans2-en-indic-dist-200M"

# App locale code -> IndicTrans2 FLORES language tag
TARGETS = {
    "hi": "hin_Deva",
    "te": "tel_Telu",
    "ta": "tam_Taml",
    "kn": "kan_Knda",
    "ml": "mal_Mlym",
}
SRC_LANG = "eng_Latn"

# Strings (exact match) that should never be translated.
DO_NOT_TRANSLATE = {"QuickScanZ", "OTP", "AI", "PWA", "Google", "Pro", "SMS"}

BATCH_SIZE = 24
MAX_LEN = 256

META = {
    "vendored_from": "@pranix/i18n (generated by translate_catalog.py via IndicTrans2)",
    "note": "Indic locales are machine-translated (IndicTrans2 dist-200M) and pending native review.",
    "locales": ["en", "hi", "te", "ta", "kn", "ml"],
}

# ---- Translation -----------------------------------------------------------

def load_model():
    import torch  # noqa: F401  (imported for side effects / availability check)
    from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
    from IndicTransToolkit.processor import IndicProcessor

    print(f"Loading {MODEL_NAME} (first run downloads ~1GB, then it's cached)...", flush=True)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code=True)
    model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME, trust_remote_code=True)
    model.eval()
    ip = IndicProcessor(inference=True)
    return tokenizer, model, ip


def translate_batch(sentences, tgt_tag, tokenizer, model, ip):
    import torch
    batch = ip.preprocess_batch(sentences, src_lang=SRC_LANG, tgt_lang=tgt_tag)
    inputs = tokenizer(
        batch, truncation=True, padding="longest",
        return_tensors="pt", return_attention_mask=True,
    )
    with torch.no_grad():
        generated = model.generate(
            **inputs, use_cache=True, min_length=0, max_length=MAX_LEN,
            num_beams=5, num_return_sequences=1,
        )
    decoded = tokenizer.batch_decode(
        generated, skip_special_tokens=True, clean_up_tokenization_spaces=True,
    )
    return ip.postprocess_batch(decoded, lang=tgt_tag)


def translate_catalog(catalog_en, tokenizer, model, ip):
    keys = list(catalog_en.keys())
    # Split into the strings we actually translate vs. the ones we pass through.
    translate_idx = [i for i, k in enumerate(keys)
                     if catalog_en[k].strip() and catalog_en[k] not in DO_NOT_TRANSLATE]
    tables = {"en": dict(catalog_en)}

    for loc, tag in TARGETS.items():
        print(f"\nTranslating -> {loc} ({tag})  [{len(translate_idx)} strings]", flush=True)
        out = dict(catalog_en)  # start from English; pass-through values stay as-is
        for start in range(0, len(translate_idx), BATCH_SIZE):
            chunk = translate_idx[start:start + BATCH_SIZE]
            sents = [catalog_en[keys[i]] for i in chunk]
            results = translate_batch(sents, tag, tokenizer, model, ip)
            for i, txt in zip(chunk, results):
                out[keys[i]] = txt
            print(f"  ...{min(start + BATCH_SIZE, len(translate_idx))}/{len(translate_idx)}", flush=True)
        tables[loc] = out
    return tables


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--in", dest="infile", default="catalog_en.json")
    parser.add_argument("--out", dest="outfile", default="messages.json")
    args = parser.parse_args()

    with open(args.infile, "r", encoding="utf-8") as f:
        catalog_en = json.load(f)
    if not isinstance(catalog_en, dict) or not catalog_en:
        print("catalog_en.json must be a non-empty object of key -> English string", file=sys.stderr)
        sys.exit(1)

    tokenizer, model, ip = load_model()
    tables = translate_catalog(catalog_en, tokenizer, model, ip)

    output = {"_meta": META}
    output.update(tables)

    with open(args.outfile, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
        f.write("\n")

    print(f"\nDone. Wrote {args.outfile} with {len(catalog_en)} keys x 6 languages.", flush=True)
    print("Review the Indic output (esp. short labels) before relying on it publicly.", flush=True)


if __name__ == "__main__":
    main()
